apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-vi
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: guestbook-vi
  template:
    metadata:
      labels:
        app: guestbook-vi
      annotations:
        moja: ciekawa adnotacja
    spec:
      containers:
      - name: myapp
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "1"
        readinessProbe:
          httpGet:
            port: http
            path: /
      restartPolicy: Always
